# Generated by Django 4.2.3 on 2023-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
