# Generated by Django 4.2.3 on 2023-07-16 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_alter_location_city_alter_location_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ip',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=55.7558),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.6173),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
