# Generated by Django 4.2.3 on 2023-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_remove_location_city_remove_location_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=37.6173),
        ),
    ]
