# Generated by Django 4.2.3 on 2023-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user_country',
            field=models.OneToOneField(on_delete=models.SET('Russia'), to='maps.location'),
        ),
    ]
