# Generated by Django 4.2.3 on 2023-07-17 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_userlocation_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.location'),
        ),
    ]
