# Generated by Django 4.2.3 on 2023-07-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_alter_userlocation_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user_country',
            field=models.CharField(max_length=200),
        ),
    ]
