# Generated by Django 4.2.3 on 2023-07-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_alter_userlocation_user_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
